import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased flex flex-col h-full`}>
        <div className="w-full">
          <Header />
          <main className="flex-1">
            <Toaster position="top-center" />
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
